kind: pipeline
type: kubernetes
name: default

steps:
- name: build image
  image: alpine
  commands:
  - docker build . -t localhost:32000/freshpanbot:latest
  - docker push localhost:32000/freshpanbot
