kind: pipeline
type: kubernetes
name: freshpanbot
steps:
- name: build
  image: docker:dind
  volumes:
  - name: docker_sock
    path: /var/run
  commands:
  - export DRONE_COMMIT_SHA=${DRONE_COMMIT_SHA:0:7}
  - docker build . -t localhost:32000/freshpanbot:latest -t localhost:32000/freshpanbot:${DRONE_COMMIT_SHA:0:7}
  - docker push localhost:32000/freshpanbot

- name: deliver
  image: sinlead/drone-kubectl
  network_mode: "host"
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - kubectl apply -f deployment.yml
    - kubectl rollout restart -n default deployment freshpanbot-app

volumes:
  - name: docker_sock
    host:
      path: /var/run