kind: pipeline
type: kubernetes
name: freshpanbot
steps:
- name: build-and-push
  image: plugins/kaniko
  settings:
    registry:
      from_secret: K8S_REGISTRY
    repo: registry-service.container-registry:5000/${DRONE_REPO_NAME,,}
    username:
      from_secret: REGISTRY_USERNAME
    password:
      from_secret: REGISTRY_PASSWORD
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:7}
    insecure: true  # if using HTTP or self-signed certs
    skip_tls_verify: true  # if your registry uses self-signed TLS

- name: update manifest repo
  image: alpine/git
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
    - export IMAGE_TAG="registry-service.container-registry:5000/${DRONE_REPO_NAME,,}:${DRONE_COMMIT_SHA:0:7}"
    - export LINE=".spec.template.spec.containers[0].image |= \"$IMAGE_TAG\""

    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - chmod -R 400 ~/.ssh

    - git clone git@github.com:thommath/Homeserver-CD.git
    - cd Homeserver-CD

    - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq
    - chmod +x yq
    - ./yq e -i "$LINE" 'freshpanbot/deployment.yaml'
    - git add freshpanbot/deployment.yaml
    - git commit -m "Bump ${DRONE_REPO_NAME,,} to ${DRONE_COMMIT_SHA:0:7}"
    - git push

volumes:
  - name: docker_sock
    host:
      path: /var/run