kind: pipeline
type: kubernetes
name: freshpanbot

steps:
- name: build
  image: docker
  commands:
  - docker build . -t localhost:32000/freshpanbot:latest
  - docker push localhost:32000/freshpanbot
