kind: pipeline
type: kubernetes
name: freshpanbot
steps:
- name: build
  image: docker:dind
  volumes:
  - name: docker_sock
    path: /var/run
  commands:
  - docker build .

- name: publish
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run
  settings:
    repo: localhost:32000/freshpanbot
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]

- name: deliver
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - kubectl apply -f deployment.yml

volumes:
  - name: docker_sock
    host:
      path: /var/run