kind: pipeline
type: kubernetes
name: freshpanbot
steps:
- name: publish
 image: plugins/docker
 settings:
   repo: localhost:32000/freshpanbot
   tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]

- name: deliver
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - kubectl apply -f deployment.yml