kind: pipeline
type: kubernetes
name: freshpanbot

steps:
- name: build
  image: docker:dind
  volumes:
  - name: docker_sock
    path: /var/run
  commands:
  - docker build . -t freshpanbot:latest
  - docker push localhost:32000/freshpanbot

volumes:
  - name: docker_sock
    host:
      path: /var/run