apiVersion: v1
kind: Service
metadata:
  name: freshpanbot-service
spec:
  selector:
    name: freshpanbot-app
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshpanbot-app
spec:
  selector:
    matchLabels:
      name: freshpanbot-app
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: freshpanbot-app
    spec:
      containers:
      - name: panbot-app
        image: localhost:32000/freshpanbot
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
