// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/add.ts";
import * as $1 from "./routes/api/addPreset.ts";
import * as $2 from "./routes/api/cancel.ts";
import * as $3 from "./routes/api/deletePreset.ts";
import * as $4 from "./routes/api/get.ts";
import * as $5 from "./routes/api/print.ts";
import * as $6 from "./routes/api/redis.ts";
import * as $7 from "./routes/api/set.ts";
import * as $8 from "./routes/drawing.tsx";
import * as $9 from "./routes/history.tsx";
import * as $10 from "./routes/image.tsx";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/printQueue.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Drawing.tsx";
import * as $$2 from "./islands/ImageHandler.tsx";
import * as $$3 from "./islands/Presets.tsx";
import * as $$4 from "./islands/Preview.tsx";
import * as $$5 from "./islands/addPreset.tsx";
import * as $$6 from "./islands/printButtons.tsx";
import * as $$7 from "./islands/printThis.tsx";

const manifest = {
  routes: {
    "./routes/api/add.ts": $0,
    "./routes/api/addPreset.ts": $1,
    "./routes/api/cancel.ts": $2,
    "./routes/api/deletePreset.ts": $3,
    "./routes/api/get.ts": $4,
    "./routes/api/print.ts": $5,
    "./routes/api/redis.ts": $6,
    "./routes/api/set.ts": $7,
    "./routes/drawing.tsx": $8,
    "./routes/history.tsx": $9,
    "./routes/image.tsx": $10,
    "./routes/index.tsx": $11,
    "./routes/printQueue.tsx": $12,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Drawing.tsx": $$1,
    "./islands/ImageHandler.tsx": $$2,
    "./islands/Presets.tsx": $$3,
    "./islands/Preview.tsx": $$4,
    "./islands/addPreset.tsx": $$5,
    "./islands/printButtons.tsx": $$6,
    "./islands/printThis.tsx": $$7,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
